import type {
  Room,
  Lecturer,
  Course,
  Schedule,
  ScheduleEntry,
  DashboardStats,
  OptimizationProgress,
} from './types'

// ==================== MOCK DATA SESUAI STRUCTURE DATA_UISI.XLSX ====================

export const mockRooms: Room[] = [
  { id: 'room-1', code: 'CM-101', name: 'Cendekia Merdeka 101', type: 'theory', capacity: 50 },
  { id: 'room-2', code: 'CM-102', name: 'Cendekia Merdeka 102', type: 'theory', capacity: 50 },
  { id: 'room-3', code: 'CM-Lab1', name: 'Lab Komputer 1', type: 'lab_multimedia', capacity: 40 },
  { id: 'room-4', code: 'CM-Lab2', name: 'Lab Komputer 2', type: 'lab_multimedia', capacity: 40 },
  { id: 'room-5', code: 'G4-R1', name: 'Gedung 4 Ruang 1', type: 'theory', capacity: 60 },
  { id: 'room-6', code: 'G4-R2', name: 'Gedung 4 Ruang 2', type: 'theory', capacity: 60 },
  { id: 'room-7', code: 'G5-Lab1', name: 'Lab Gedung 5', type: 'lab_multimedia', capacity: 30 },
  { id: 'room-8', code: 'B3-R1', name: 'Blok 3 Ruang 1', type: 'theory', capacity: 25 },
]

export const mockLecturers: Lecturer[] = [
  {
    id: 'lec-1',
    prodi: 'INFORMATIKA',
    code: 'NGT',
    name: 'Prof. Dr. Ngesti Yuni Sugiharti, S.T., M.Kom.',
    preferredTime: '08:00-16:00',
    researchDay: 'Friday',
    transitTime: 30,
    maxDailyPeriods: 4,
    preferredRoom: 'CM-101,CM-102',
  },
  {
    id: 'lec-2',
    prodi: 'INFORMATIKA',
    code: 'BMR',
    name: 'Dr. Bima Sakti, S.T., M.T.',
    preferredTime: '07:30-15:30',
    researchDay: 'Thursday',
    transitTime: 20,
    maxDailyPeriods: 5,
    preferredRoom: 'CM-Lab1,G4-R1',
  },
  {
    id: 'lec-3',
    prodi: 'SISTEM INFORMASI',
    code: 'TKN',
    name: 'Trias Suryana, S.Kom., M.T.',
    preferredTime: '09:00-17:00',
    researchDay: 'Wednesday',
    transitTime: 25,
    maxDailyPeriods: 4,
    preferredRoom: 'CM-101,CM-Lab2',
  },
  {
    id: 'lec-4',
    prodi: 'MANAJEMEN',
    code: 'MDI',
    name: 'Dr. Madiun Tjahyono, S.E., M.M.',
    preferredTime: '08:00-16:00',
    researchDay: 'Monday',
    transitTime: 15,
    maxDailyPeriods: 6,
    preferredRoom: 'G4-R1,G4-R2',
  },
  {
    id: 'lec-5',
    prodi: 'Akuntansi',
    code: 'FRD',
    name: 'Feri Raharjo, S.E., M.Ak.',
    preferredTime: '10:00-18:00',
    researchDay: 'Tuesday',
    transitTime: 20,
    maxDailyPeriods: 5,
    preferredRoom: 'CM-102,B3-R1',
  },
]

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    prodi: 'Informatika',
    kelas: 'IF-3A',
    kodeMatakuliah: 'IF13KA14',
    mataKuliah: 'Kalkulus',
    sks: 4,
    jenis: 'wajib',
    peserta: 35,
    kodeDosen1: 'NGT',
    kodeDosen2: 'PAY',
    kodeDosenProdiLain1: '',
    kodeDosenProdiLain2: '',
    classType: 'pagi',
    shouldOnTheLab: false,
    rooms: 'CM-101,CM-102',
  },
  {
    id: 'course-2',
    prodi: 'Informatika',
    kelas: 'IF-3A',
    kodeMatakuliah: 'IF13AS13',
    mataKuliah: 'Algoritma dan Struktur Data',
    sks: 3,
    jenis: 'wajib',
    peserta: 37,
    kodeDosen1: 'BMR',
    kodeDosen2: '',
    kodeDosenProdiLain1: '',
    kodeDosenProdiLain2: '',
    classType: 'pagi',
    shouldOnTheLab: true,
    rooms: 'CM-Lab1,CM-Lab2',
  },
  {
    id: 'course-3',
    prodi: 'Sistem Informasi',
    kelas: 'SI-3A',
    kodeMatakuliah: 'IS13EB02',
    mataKuliah: 'Pengantar Ekonomi dan Bisnis',
    sks: 2,
    jenis: 'wajib',
    peserta: 45,
    kodeDosen1: 'MAL',
    kodeDosen2: '',
    kodeDosenProdiLain1: '',
    kodeDosenProdiLain2: '',
    classType: 'pagi',
    shouldOnTheLab: false,
    rooms: 'G4-R1,G4-R2',
  },
  {
    id: 'course-4',
    prodi: 'Manajemen',
    kelas: 'MG-5A',
    kodeMatakuliah: 'MG13KP13',
    mataKuliah: 'Kepemimpinan',
    sks: 3,
    jenis: 'pilihan',
    peserta: 40,
    kodeDosen1: 'MDI',
    kodeDosen2: '',
    kodeDosenProdiLain1: '',
    kodeDosenProdiLain2: '',
    classType: 'pagi',
    shouldOnTheLab: false,
    rooms: 'G4-R1',
  },
  {
    id: 'course-5',
    prodi: 'Akuntansi',
    kelas: 'AK-3A',
    kodeMatakuliah: 'AB13A803',
    mataKuliah: 'Manajemen Keuangan',
    sks: 3,
    jenis: 'wajib',
    peserta: 40,
    kodeDosen1: 'FRD',
    kodeDosen2: '',
    kodeDosenProdiLain1: '',
    kodeDosenProdiLain2: '',
    classType: 'pagi',
    shouldOnTheLab: false,
    rooms: 'CM-102',
  },
]

export const mockScheduleEntries: ScheduleEntry[] = [
  {
    id: 'entry-1',
    courseId: 'course-1',
    lecturerId: 'lec-1',
    roomId: 'room-1',
    timeSlot: { day: 'Monday', startTime: '09:00', endTime: '10:00' },
  },
  {
    id: 'entry-2',
    courseId: 'course-1',
    lecturerId: 'lec-1',
    roomId: 'room-3',
    timeSlot: { day: 'Wednesday', startTime: '09:00', endTime: '10:00' },
  },
  {
    id: 'entry-3',
    courseId: 'course-2',
    lecturerId: 'lec-1',
    roomId: 'room-2',
    timeSlot: { day: 'Monday', startTime: '11:00', endTime: '12:00' },
  },
  {
    id: 'entry-4',
    courseId: 'course-3',
    lecturerId: 'lec-2',
    roomId: 'room-1',
    timeSlot: { day: 'Tuesday', startTime: '10:00', endTime: '11:30' },
  },
  {
    id: 'entry-5',
    courseId: 'course-4',
    lecturerId: 'lec-3',
    roomId: 'room-1',
    timeSlot: { day: 'Monday', startTime: '14:00', endTime: '15:00' },
  },
  {
    id: 'entry-6',
    courseId: 'course-5',
    lecturerId: 'lec-3',
    roomId: 'room-5',
    timeSlot: { day: 'Thursday', startTime: '09:00', endTime: '10:30' },
  },
  {
    id: 'entry-7',
    courseId: 'course-6',
    lecturerId: 'lec-4',
    roomId: 'room-2',
    timeSlot: { day: 'Tuesday', startTime: '14:00', endTime: '15:00' },
  },
  {
    id: 'entry-8',
    courseId: 'course-7',
    lecturerId: 'lec-5',
    roomId: 'room-3',
    timeSlot: { day: 'Friday', startTime: '10:00', endTime: '11:30' },
  },
  {
    id: 'entry-9',
    courseId: 'course-8',
    lecturerId: 'lec-2',
    roomId: 'room-3',
    timeSlot: { day: 'Wednesday', startTime: '14:00', endTime: '15:30' },
  },
  {
    id: 'entry-10',
    courseId: 'course-4',
    lecturerId: 'lec-3',
    roomId: 'room-1',
    timeSlot: { day: 'Wednesday', startTime: '11:00', endTime: '12:00' },
  },
]

export const mockSchedule: Schedule = {
  id: 'schedule-1',
  name: 'Fall 2025 Schedule',
  semester: 'Fall',
  year: 2025,
  entries: mockScheduleEntries,
  fitness: 0.87,
  createdAt: new Date('2025-01-15'),
  updatedAt: new Date('2025-01-28'),
}

export const mockDashboardStats: DashboardStats = {
  totalCourses: mockCourses.length,
  totalLecturers: mockLecturers.length,
  totalRooms: mockRooms.length,
  scheduledSessions: mockScheduleEntries.length,
  conflictCount: 2,
  utilizationRate: 0.73,
  lastOptimizationFitness: 0.87,
}

export const mockOptimizationProgress: OptimizationProgress = {
  currentIteration: 0,
  totalIterations: 20000,
  bestCost: 145.5,
  currentCost: 145.5,
  hardConstraintViolations: 0,
  softConstraintViolations: 8,
  isRunning: false,
}

// SA Optimization history for charts (Simulated Annealing progress)
export const mockFitnessHistory = [
  { iteration: 0, currentCost: 145.5, bestCost: 145.5 },
  { iteration: 1000, currentCost: 98.2, bestCost: 92.8 },
  { iteration: 2000, currentCost: 76.4, bestCost: 71.2 },
  { iteration: 3000, currentCost: 62.1, bestCost: 55.7 },
  { iteration: 4000, currentCost: 51.3, bestCost: 45.2 },
  { iteration: 5000, currentCost: 44.8, bestCost: 38.6 },
  { iteration: 6000, currentCost: 39.2, bestCost: 33.4 },
  { iteration: 7000, currentCost: 35.7, bestCost: 30.1 },
  { iteration: 8000, currentCost: 32.4, bestCost: 28.5 },
  { iteration: 9000, currentCost: 30.8, bestCost: 27.8 },
  { iteration: 10000, currentCost: 29.5, bestCost: 27.3 },
  { iteration: 11000, currentCost: 28.7, bestCost: 27.0 },
  { iteration: 12000, currentCost: 28.2, bestCost: 26.9 },
  { iteration: 13000, currentCost: 27.9, bestCost: 26.8 },
  { iteration: 14000, currentCost: 27.8, bestCost: 26.8 },
  { iteration: 15000, currentCost: 27.7, bestCost: 26.8 },
  { iteration: 16000, currentCost: 27.8, bestCost: 26.8 },
  { iteration: 17000, currentCost: 27.6, bestCost: 26.8 },
  { iteration: 18000, currentCost: 27.7, bestCost: 26.8 },
  { iteration: 19000, currentCost: 27.6, bestCost: 26.8 },
  { iteration: 20000, currentCost: 26.9, bestCost: 26.8 },
]

// Room utilization data for charts
export const mockRoomUtilization = [
  { name: 'LT-101', utilization: 75, capacity: 150 },
  { name: 'LT-102', utilization: 68, capacity: 100 },
  { name: 'Lab-A1', utilization: 82, capacity: 40 },
  { name: 'Lab-A2', utilization: 71, capacity: 35 },
  { name: 'SR-201', utilization: 55, capacity: 30 },
  { name: 'SR-202', utilization: 63, capacity: 25 },
]
// Weekly distribution data
export const mockWeeklyDistribution = [
  { day: 'Mon', sessions: 12, hours: 14 },
  { day: 'Tue', sessions: 10, hours: 12 },
  { day: 'Wed', sessions: 11, hours: 13 },
  { day: 'Thu', sessions: 9, hours: 11 },
  { day: 'Fri', sessions: 8, hours: 10 },
]
